# Generated by Django 4.0.3 on 2022-04-19 16:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import galleryfield.fields
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='my_images')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='gallery',
            field=galleryfield.fields.GalleryField(blank=True, null=True, target_model='posts.MyImage'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to=posts.models.user_post_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png'])]),
        ),
    ]
