# Generated by Django 4.0.3 on 2022-04-19 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_myimage_post_gallery_alter_comment_post_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyImage',
        ),
        migrations.RemoveField(
            model_name='post',
            name='gallery',
        ),
    ]
